build.sbt
project/build.properties
project/plugins.sbt
schemas/README.md

- added modules: atlas, electrophysiology,
experiment, commons,core,morphology,simulation
- added plugins sbt and build properties files

Initialized build sbt file:

---

modules/nexus-schemas/src/main/resources/contexts/nexus/core/mediatype/v0.1.0.json
modules/nexus-schemas/src/main/resources/contexts/nexus/core/schemaorgrelease3_3/v0.1.0.json
modules/nexus-schemas/src/main/resources/schemas/nexus/core/mediatype/v0.1.0.json
modules/nexus-schemas/src/main/resources/schemas/nexus/schemaorg/identifier/v0.1.0.json
modules/nexus-schemas/src/main/resources/schemas/nexus/schemaorg/organization/v0.1.0.json
modules/nexus-schemas/src/main/resources/schemas/nexus/schemaorg/person/v0.1.0.json
modules/nexus-schemas/src/main/resources/schemas/nexus/schemaorg/propertyvalue/v0.1.0.json
modules/nexus-schemas/src/main/resources/schemas/nexus/schemaorgsh/identifier/v0.1.0.json
modules/nexus-schemas/src/main/resources/schemas/nexus/schemaorgsh/organization/v0.1.0.json
modules/nexus-schemas/src/main/resources/schemas/nexus/schemaorgsh/person/v0.1.0.json
modules/nexus-schemas/src/main/resources/schemas/nexus/schemaorgsh/propertyvalue/v0.1.0.json
modules/nexus-schemas/src/main/resources/schemas/nexus/schemaorgsh/quantitativevalue/v0.1.0.json
modules/nexus-schemas/src/test/resources/data/nexus/core/mediatype/v0.1.0/all-fields.json
modules/nexus-schemas/src/test/resources/data/nexus/core/mediatype/v0.1.0/min-fields.json
modules/nexus-schemas/src/test/resources/invalid/nexus/core/mediatype/v0.1.0/missing-name.json
modules/nexus-schemas/src/test/resources/invalid/nexus/core/mediatype/v0.1.0/missing-type.json
modules/nexus-schemas/src/test/resources/invalid/nexus/core/mediatype/v0.1.0/more-than-one-defining-resource.json
modules/nexus-schemas/src/test/resources/invalid/nexus/core/mediatype/v0.1.0/non-IRI-identifier.json
modules/nexus-schemas/src/test/resources/invalid/nexus/core/mediatype/v0.1.0/non-IRI-isDefinedBy.json
modules/nexus-schemas/src/test/resources/invalid/nexus/core/mediatype/v0.1.0/non-IRI-sameAs.json
modules/nexus-schemas/src/test/resources/invalid/nexus/core/mediatype/v0.1.0/non-IRI-seeAlso.json
modules/nexus-schemas/src/test/resources/invalid/nexus/core/mediatype/v0.1.0/non-boolean-deprecated.json
modules/nexus-schemas/src/test/resources/invalid/nexus/core/mediatype/v0.1.0/wrong-name-pattern.json
modules/nexus-schemas/src/test/resources/invalid/nexus/core/mediatype/v0.1.0/wrong-type.json

- added mediatype schemas and contexts
- added schemaorg schemas and contexts

Added nexus-schemas:

---

modules/commons/src/main/resources/contexts/neurosciencegraph/core/data/v0.1.0.json
modules/commons/src/main/resources/contexts/neurosciencegraph/core/schema/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/activity/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/activitywithprotocol/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/brainlocation/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/entity/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/experiment/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/identifier/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/labeledontologyentity/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/measurement/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/mediatype/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/organization/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/person/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/protocol/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/quantitativevalue/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/sizedcollection/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/typedlabeledontologyterm/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/vector3d/v0.1.0.json

Initialized common and shared shapes

---

modules/experiment/src/main/resources/schemas/neurosciencegraph/experiment/brainslicing/v0.1.0.json
modules/experiment/src/main/resources/schemas/neurosciencegraph/experiment/patchedcell/v0.1.0.json
modules/experiment/src/main/resources/schemas/neurosciencegraph/experiment/patchedcellcollection/v0.1.0.json
modules/experiment/src/main/resources/schemas/neurosciencegraph/experiment/patchedslice/v0.1.0.json
modules/experiment/src/main/resources/schemas/neurosciencegraph/experiment/subjectcollection/v0.1.0.json
modules/experiment/src/main/resources/schemas/neurosciencegraph/experiment/wholecellpatchclamp/v0.1.0.json
modules/experiment/src/test/resources/data/neurosciencegraph/experiment/brainslicing/v0.1.0/min-fields.json
modules/experiment/src/test/resources/data/neurosciencegraph/experiment/brainslicing/v0.1.0/neobase_example.json
modules/experiment/src/test/resources/data/neurosciencegraph/experiment/patchedcell/v0.1.0/min-fields.json
modules/experiment/src/test/resources/data/neurosciencegraph/experiment/patchedcell/v0.1.0/neobase_example.json
modules/experiment/src/test/resources/data/neurosciencegraph/experiment/patchedcellcollection/v0.1.0/min-fields.json
modules/experiment/src/test/resources/data/neurosciencegraph/experiment/patchedcellcollection/v0.1.0/neobase_example.json
modules/experiment/src/test/resources/data/neurosciencegraph/experiment/patchedslice/v0.1.0/min-fields.json
modules/experiment/src/test/resources/data/neurosciencegraph/experiment/patchedslice/v0.1.0/neobase_example.json
modules/experiment/src/test/resources/data/neurosciencegraph/experiment/subjectcollection/v0.1.0/all-fields.json
modules/experiment/src/test/resources/data/neurosciencegraph/experiment/subjectcollection/v0.1.0/min-fields-name.json
modules/experiment/src/test/resources/data/neurosciencegraph/experiment/wholecellpatchclamp/v0.1.0/min-fields.json
modules/experiment/src/test/resources/data/neurosciencegraph/experiment/wholecellpatchclamp/v0.1.0/neobase_example.json
modules/experiment/src/test/resources/invalid/neurosciencegraph/experiment/brainslicing/v0.1.0/missing-used.json
modules/experiment/src/test/resources/invalid/neurosciencegraph/experiment/brainslicing/v0.1.0/wrong-type.json
modules/experiment/src/test/resources/invalid/neurosciencegraph/experiment/patchedcell/v0.1.0/wrong-type.json
modules/experiment/src/test/resources/invalid/neurosciencegraph/experiment/patchedcellcollection/v0.1.0/missing-required-member.json
modules/experiment/src/test/resources/invalid/neurosciencegraph/experiment/patchedcellcollection/v0.1.0/wrong-type-ignored.json
modules/experiment/src/test/resources/invalid/neurosciencegraph/experiment/patchedslice/v0.1.0/wrong-type.json
modules/experiment/src/test/resources/invalid/neurosciencegraph/experiment/subjectcollection/v0.1.0/missing-required-member.json
modules/experiment/src/test/resources/invalid/neurosciencegraph/experiment/subjectcollection/v0.1.0/missing-required-name.json
modules/experiment/src/test/resources/invalid/neurosciencegraph/experiment/wholecellpatchclamp/v0.1.0/wrong-type.json

Initialized experiment related shapes

---

modules/atlas/src/main/resources/schemas/neurosciencegraph/atlas/atlasconstruction/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/collection/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/emptycollection/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/subjectcollection/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/typedlabeledontologyterm/v0.1.0.json
modules/core/src/main/resources/schemas/neurosciencegraph/core/collection/v0.1.0.json
modules/core/src/main/resources/schemas/neurosciencegraph/core/emptycollection/v0.1.0.json
modules/core/src/main/resources/schemas/neurosciencegraph/core/subject/v0.1.0.json
modules/electrophysiology/src/main/resources/schemas/neurosciencegraph/electrophysiology/stimulusexperiment/v0.1.0.json
modules/electrophysiology/src/main/resources/schemas/neurosciencegraph/electrophysiology/trace/v0.1.0.json
modules/electrophysiology/src/main/resources/schemas/neurosciencegraph/electrophysiology/tracegeneration/v0.1.0.json
modules/experiment/src/main/resources/schemas/neurosciencegraph/experiment/brainslicing/v0.1.0.json
modules/experiment/src/main/resources/schemas/neurosciencegraph/experiment/patchedcell/v0.1.0.json
modules/experiment/src/main/resources/schemas/neurosciencegraph/experiment/subjectcollection/v0.1.0.json
modules/morphology/src/main/resources/schemas/neurosciencegraph/morphology/labeledcell/v0.1.0.json
modules/morphology/src/main/resources/schemas/neurosciencegraph/morphology/reconstructedcell/v0.1.0.json
modules/morphology/src/main/resources/schemas/neurosciencegraph/morphology/reconstruction/v0.1.0.json

Renamed UnitCodeOntologyTermShape to this:UnitOntologyTermShape

Used typedlabeldontologyterm instead of labeledontologyterm schema

---

modules/core/src/main/resources/schemas/neurosciencegraph/core/subject/v0.1.0.json
modules/simulation/src/main/resources/schemas/neurosciencegraph/simulation/emodelgeneration/v0.1.0.json

Fixed wrong references for generation and typedlabeledontologyterm

---

modules/commons/src/main/resources/schemas/neurosciencegraph/commons/activity/v0.1.3.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/protocol/v0.1.3.json
modules/core/src/main/resources/schemas/neurosciencegraph/core/activity/v0.1.3.json
modules/core/src/main/resources/schemas/neurosciencegraph/core/protocol/v0.1.3.json

Renamed PropetyShape to PropertyShape.
Fixes: #84

Corrected HadProtocolValueShape

---

modules/commons/src/main/resources/schemas/neurosciencegraph/commons/activity/v0.1.4.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/experimentalactivity/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/experimentalprotocol/v0.1.0.json
modules/commons/src/main/resources/schemas/neurosciencegraph/commons/protocol/v0.1.4.json
modules/core/src/main/resources/schemas/neurosciencegraph/core/experimentalactivity/v0.1.0.json
modules/core/src/main/resources/schemas/neurosciencegraph/core/experimentalprotocol/v0.1.0.json
modules/core/src/main/resources/schemas/neurosciencegraph/core/protocol/v0.1.4.json
modules/experiment/src/main/resources/schemas/neurosciencegraph/experiment/protocol/v0.1.0.json

Created experimental protocol schema

---

modules/experiment/src/main/resources/schemas/neurosciencegraph/experiment/patchedcell/v0.2.1.json
modules/experiment/src/main/resources/schemas/neurosciencegraph/experiment/patchedslice/v0.1.1.json

- bath solution
- pipette solution
- recording temperature
Also add a field for the cell morphology

Add additional metadata needed for slice recordings

---

modules/electrophysiology/src/main/resources/schemas/neurosciencegraph/electrophysiology/stimulusexperiment/v1.0.0.json
modules/electrophysiology/src/main/resources/schemas/neurosciencegraph/electrophysiology/trace/v1.0.0.json
modules/electrophysiology/src/main/resources/schemas/neurosciencegraph/electrophysiology/tracegeneration/v1.0.0.json
modules/electrophysiology/src/test/resources/data/neurosciencegraph/electrophysiology/stimulusexperiment/v1.0.0/min-fields.json
modules/electrophysiology/src/test/resources/data/neurosciencegraph/electrophysiology/stimulusexperiment/v1.0.0/neobase_example.json
modules/electrophysiology/src/test/resources/data/neurosciencegraph/electrophysiology/trace/v1.0.0/all-fields.json
modules/electrophysiology/src/test/resources/data/neurosciencegraph/electrophysiology/trace/v1.0.0/min-fields.json
modules/electrophysiology/src/test/resources/data/neurosciencegraph/electrophysiology/trace/v1.0.0/neobase_example.json
modules/electrophysiology/src/test/resources/data/neurosciencegraph/electrophysiology/tracegeneration/v1.0.0/min-fields.json
modules/electrophysiology/src/test/resources/data/neurosciencegraph/electrophysiology/tracegeneration/v1.0.0/neobase_example.json

Use of rdf:type for stimulus types instead of nsg:stimulusType

Updated ephys schemas to reuse latest versions of activity and ontology term schemas

---

modules/commons/src/main/resources/contexts/neurosciencegraph/core/data/v1.0.1.json

* Added @vocab
* Added nsg:waveNumberRange
* Removed duplicate of subcellularMechanism

Created data context v1.0.1

---

modules/commons/src/main/resources/contexts/neurosciencegraph/core/data/v1.0.3.json

Create data context v1.0.3 to accommodate storage type in distribution object

---

modules/simulation/src/main/resources/schemas/neurosciencegraph/simulation/modelscript/v0.1.0.json

as it is superseeded by EModelScript

Deprecate ModelScript

---

modules/commons/src/main/resources/contexts/neurosciencegraph/core/data/v0.3.1.json

Used @type instead of type

---

modules/commons/src/main/resources/contexts/neurosciencegraph/core/data/v0.3.0.json
modules/commons/src/main/resources/contexts/neurosciencegraph/core/data/v0.3.1.json
modules/commons/src/main/resources/contexts/neurosciencegraph/core/data/v0.3.2.json
modules/commons/src/main/resources/contexts/neurosciencegraph/core/data/v1.0.0.json
modules/commons/src/main/resources/contexts/neurosciencegraph/core/data/v1.0.1.json
modules/commons/src/main/resources/contexts/neurosciencegraph/core/data/v1.0.2.json
modules/commons/src/main/resources/contexts/neurosciencegraph/core/data/v1.0.3.json
modules/commons/src/main/resources/contexts/neurosciencegraph/core/data/v1.0.4.json

Used @type instead of type when defining brainRegion prefix mapping

---

modules/commons/src/main/resources/contexts/neurosciencegraph/core/data/v1.0.5.json

* added schema:image
* added nsg:repository
* added nsg:atlasSpatialReferenceSystem
* added nsg:mTypeAnnotation
Fixes #190

Created data context v1.0.5

---

modules/simulation/src/main/resources/schemas/neurosciencegraph/simulation/bluepyefeconfiguration/v0.1.4.json

removed experimentalTraceLocation as it is part of featureExtractionConfiguration

---

modules/simulation/src/main/resources/schemas/neurosciencegraph/simulation/morphologydiversification/v0.1.3.json

MorphologyDiversification should have at most one ReconstructedCellRelease
and at least one Configuration

fix morphologydiversification schema

---

taxonomies/stimulus-types.ttl

Created .ttl file with stimulus type taxonomy

---

README.md

Fixed links in tutorial section in README.md

---

modules/commons/src/main/resources/schemas/neurosciencegraph/commons/identifier/v0.2.1.json
modules/core/src/main/resources/schemas/neurosciencegraph/core/subject/v1.0.0.json

in neurosciencegraph/commons/identifier and  neurosciencegraph/core/subject

Fixed typos

---

ontologies/core-ontology.ttl
shapes/neurosciencegraph/commons/typedlabeledontologyterm/schema.json

nxv => https://bluebrain.github.io/nexus/vocabulary/
nsg => https://neuroshapes.org/

Updated nsg prefix mapping to https://neuroshapes.org/

---

shapes/neurosciencegraph/commons/identifier/schema.json

Fixed WithGridIdentifierPropertyShapes

---

shapes/neurosciencegraph/commons/brainlocation/schema.json

Added nsg:layer property to BrainLocation schema

---

shapes/neurosciencegraph/datashapes/experiment/patchedslice/schema.json

Removed minCount for hasPart property

---

shapes/neurosciencegraph/datashapes/experiment/cellcounting/schema.json

Added cellcounting schema

---

contexts/data.json

preSynaptic: property used for SynapticConnectivity data
postSynaptic: property used for SynapticConnectivity data
store: property used in distribution to indicate which store was used

Add preSynaptic, postSynaptic and store property
